# Generated by Django 4.2.5 on 2023-09-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='selectedmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatmodel'),
        ),
    ]
