# Generated by Django 3.1.3 on 2023-09-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='selectedmodel',
            field=models.TextField(default='AI Chatbot'),
        ),
    ]
