# Generated by Django 4.2.5 on 2023-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_selectedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='greeting',
            field=models.TextField(default='Hi, I am, you can ask me anything.', null=True),
        ),
    ]
