# Generated by Django 3.1.3 on 2023-09-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_selectedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='modelrole',
            field=models.TextField(default='assistant'),
        ),
        migrations.AddField(
            model_name='chat',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
