# Generated by Django 4.2.5 on 2023-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmodel_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='cutename',
            field=models.TextField(default='', null=True),
        ),
    ]
